export const planetsData = [
  {
    name: "Sun",
    radius: 5,
    distanceFromSun: 0,
    color: 0xffcc00,
    texture: "textures/sun.jpg",
    orbitSpeed: 0,
    rotationSpeed: 0.01,
    rings: [],
    moons: [],
  },
  {
    name: "Mercury",
    radius: 1,
    distanceFromSun: 10,
    color: 0xaaaaaa,
    texture: "textures/mercury.jpg",
    orbitSpeed: 0.00833,
    rotationSpeed: 0.01,
    rings: [],
    moons: [],
  },
  {
    name: "Venus",
    radius: 1.5,
    distanceFromSun: 18.6,
    color: 0xffddaa,
    texture: "textures/venus.jpg",
    orbitSpeed: 0.00322,
    rotationSpeed: 0.005,
    rings: [],
    moons: [],
  },
  {
    name: "Earth",
    radius: 2,
    distanceFromSun: 25.8,
    color: 0x2194ce,
    texture: "textures/earth.jpg",
    orbitSpeed: 0.002,
    rotationSpeed: 0.01,
    rings: [],
    moons: [
      {
        name: "Moon",
        radius: 0.3,
        distanceFromPlanet: 0.5,
        texture: "textures/moon.jpg",
        orbitSpeed: 0.0025,
        rotationSpeed: 0.01,
        isTidalyLocked: true // Moon is tidally locked to Earth
      },
    ],
  },
  {
    name: "Mars",
    radius: 1.2,
    distanceFromSun: 39.4,
    color: 0xff3300,
    texture: "textures/mars.jpg",
    orbitSpeed: 0.00106,
    rotationSpeed: 0.008,
    rings: [],
    moons: [
      {
        name: "Phobos",
        radius: 0.2,
        distanceFromPlanet: 0.5,
        texture: "textures/phobos.jpg",
        orbitSpeed: 0.002,
        rotationSpeed: 0.01,
      },
      {
        name: "Deimos",
        radius: 0.15,
        distanceFromPlanet: 1,
        texture: "textures/deimos.jpg",
        orbitSpeed: 0.0015,
        rotationSpeed: 0.01,
      },
    ],
  },
  {
    name: "Jupiter",
    radius: 4,
    distanceFromSun: 70.4,
    color: 0xffa500,
    texture: "textures/jupiter.jpg",
    orbitSpeed: 0.0001686,
    rotationSpeed: 0.02,
    rings: [],
    moons: [
      {
        name: "Io",
        radius: 0.5,
        distanceFromPlanet: 1.5,
        texture: "textures/io.png",
        orbitSpeed: 0.0025,
        rotationSpeed: 0.01,
      },
      {
        name: "Europa",
        radius: 0.4,
        distanceFromPlanet: 3,
        texture: "textures/europa.jpg",
        orbitSpeed: 0.002,
        rotationSpeed: 0.01,
      },
      {
        name: "Ganymede",
        radius: 0.6,
        distanceFromPlanet: 4.5,
        texture: "textures/ganymede.jpg",
        orbitSpeed: 0.0018,
        rotationSpeed: 0.01,
      },
      {
        name: "Callisto",
        radius: 0.7,
        distanceFromPlanet: 6.5,
        texture: "textures/callisto.jpg",
        orbitSpeed: 0.0015,
        rotationSpeed: 0.01,
      },
    ],
  },
  {
    name: "Saturn",
    radius: 3.5,
    distanceFromSun: 120.2,
    color: 0xffcc99,
    texture: "textures/saturn.jpg",
    orbitSpeed: 0.0000679,
    rotationSpeed: 0.018,
    rings: [
      {
        innerRadius: 4,
        outerRadius: 6,
        texture: "textures/saturn_ring.png",
        rotationSpeed: 0.01,
        inclination: {
          x: -Math.PI / 4,
          y: 0,
          z: Math.PI / 8,
        },
      },
    ],
    moons: [
      {
        name: "Titan",
        radius: 0.5,
        distanceFromPlanet: 3.5,
        texture: "textures/titan.jpg",
        orbitSpeed: 0.002,
        rotationSpeed: 0.01,
      },
      {
        name: "Rhea",
        radius: 0.4,
        distanceFromPlanet: 5,
        texture: "textures/rhea.jpg",
        orbitSpeed: 0.0015,
        rotationSpeed: 0.01,
      },
      {
        name: "Iapetus",
        radius: 0.3,
        distanceFromPlanet: 6.5,
        texture: "textures/iapetus.jpg",
        orbitSpeed: 0.0012,
        rotationSpeed: 0.01,
      },
    ],
  },
  {
    name: "Uranus",
    radius: 3,
    distanceFromSun: 150.2,
    color: 0x66ffff,
    texture: "textures/uranus.jpg",
    orbitSpeed: 0.0000238,
    rotationSpeed: 0.015,
    rings: [],
    moons: [
      {
        name: "Titania",
        radius: 0.4,
        distanceFromPlanet: 1.5,
        texture: "textures/titania.jpg",
        orbitSpeed: 0.0015,
        rotationSpeed: 0.01,
      },
      {
        name: "Oberon",
        radius: 0.3,
        distanceFromPlanet: 3,
        texture: "textures/oberon.jpg",
        orbitSpeed: 0.0012,
        rotationSpeed: 0.01,
      },
    ],
  },
  {
    name: "Neptune",
    radius: 2.8,
    distanceFromSun: 190.4,
    color: 0x3366ff,
    texture: "textures/neptune.jpg",
    orbitSpeed: 0.0000121,
    rotationSpeed: 0.014,
    rings: [],
    moons: [
      {
        name: "Triton",
        radius: 0.5,
        distanceFromPlanet: 1.5,
        texture: "textures/triton.jpg",
        orbitSpeed: 0.001,
        rotationSpeed: 0.01,
      },
      {
        name: "Nereid",
        radius: 0.2,
        distanceFromPlanet: 3,
        texture: "textures/nereid.jpg",
        orbitSpeed: 0.0008,
        rotationSpeed: 0.01,
      },
    ],
  },
];
